// Automatically generated by scripts/generate_projects_data.js
// Do not edit this file manually.

export interface ProjectMedia {
  name: string
  src: string
  type: 'image' | 'video' | 'pdf'
}

export interface ProjectDemo {
  type: 'image' | 'video' | 'pdf'
  src: string
}

export interface LocalProject {
  id: string
  title: string
  info: string
  skills: string[]
  demo: ProjectDemo | null
  thumbnail: string
  media: ProjectMedia[]
}

export const LOCAL_PROJECTS: LocalProject[] = [
  {
    "id": "agrivaani-multilingual-ai-agriculture-assistant-for-nepali-farmers",
    "title": "AgriVaani – Multilingual AI Agriculture Assistant for Nepali Farmers",
    "info": "Developed AgriVaani, a multilingual agriculture assistant available in Nepali, English, Maithili, and Bhojpuri. It enables farmers to onboard via voice in their own language, creating detailed profiles with AI from their introductions. Farmers can then ask agriculture-related questions (via text, image, or voice) and receive personalized answers based on their unique profiles. The app also provides location-based weather updates, daily market prices for crops, and an agriculture news feed automatically translated into their chosen language.",
    "skills": [
      "NLP",
      "LLM",
      "Python",
      "STT & TTS"
    ],
    "demo": {
      "type": "pdf",
      "src": "/projects/AgriVaani – Multilingual AI Agriculture Assistant for Nepali Farmers/Agri_appSS.pdf"
    },
    "thumbnail": "/projects/AgriVaani – Multilingual AI Agriculture Assistant for Nepali Farmers/image.png",
    "media": [
      {
        "name": "Agri_appSS.pdf",
        "src": "/projects/AgriVaani – Multilingual AI Agriculture Assistant for Nepali Farmers/Agri_appSS.pdf",
        "type": "pdf"
      },
      {
        "name": "image.png",
        "src": "/projects/AgriVaani – Multilingual AI Agriculture Assistant for Nepali Farmers/image.png",
        "type": "image"
      }
    ]
  },
  {
    "id": "nepali-sign-language-translation-character-level",
    "title": "Nepali Sign Language Translation ( Character Level )",
    "info": "NSLT (Nepali Sign Language Translator) is a deep learning project focused on character-level classification of Nepali Sign Language. Using computer vision techniques, we trained a model to recognize individual hand signs corresponding to Nepali alphabets. The system uses a webcam to capture gesture images and classifies them in real time using a convolutional neural network. This project aims to assist communication for the hearing-impaired by enabling accurate recognition of sign characters.",
    "skills": [
      "Computer Vision",
      "Deep Learning",
      "TensorFlow",
      "OpenCV",
      "Python",
      "Dataset Creation"
    ],
    "demo": {
      "type": "image",
      "src": "/projects/Nepali Sign Language Translation ( Character Level )/NSLT_image1.png"
    },
    "thumbnail": "/projects/Nepali Sign Language Translation ( Character Level )/thumbnail.png",
    "media": [
      {
        "name": "NSLT_image1.png",
        "src": "/projects/Nepali Sign Language Translation ( Character Level )/NSLT_image1.png",
        "type": "image"
      },
      {
        "name": "NSLT_image2.png",
        "src": "/projects/Nepali Sign Language Translation ( Character Level )/NSLT_image2.png",
        "type": "image"
      },
      {
        "name": "thumbnail.png",
        "src": "/projects/Nepali Sign Language Translation ( Character Level )/thumbnail.png",
        "type": "image"
      }
    ]
  },
  {
    "id": "ocr-system-for-student-mcq-answer-sheets",
    "title": "OCR System for Student MCQ Answer Sheets",
    "info": "Built a system that processes images of solved MCQ answer sheets, extracts answers using OCR, and displays results instantly in a clean UI. The solution also allows results to be downloaded in JSON format for reuse and analysis. What started as a simple idea became a valuable learning experience, and the final product worked exactly as the client envisioned.",
    "skills": [
      "Python",
      "OCR",
      "React Native",
      "Node.js",
      "LLM"
    ],
    "demo": {
      "type": "video",
      "src": "/projects/OCR System for Student MCQ Answer Sheets/OCR_video.mov"
    },
    "thumbnail": "/projects/OCR System for Student MCQ Answer Sheets/OCR_video.mov",
    "media": [
      {
        "name": "OCR_video.mov",
        "src": "/projects/OCR System for Student MCQ Answer Sheets/OCR_video.mov",
        "type": "video"
      }
    ]
  },
  {
    "id": "student-behavior-analysis-skeleton-annotation-gcn-training",
    "title": "Student Behavior Analysis - Skeleton Annotation & GCN Training",
    "info": "Built a real-time student behavior recognition system using skeleton-based GCN. My role focused on data annotation and model training — labeling the SCB dataset with both bounding boxes and 17 COCO-format keypoints per person, forming full-body skeleton graphs (joints as nodes, bones as edges) for 8 behavior classes. Trained PCCTR-GCN on 30-frame temporal sequences with pose correction for occluded joints, improving sleeping detection from 65% to 85% accuracy and achieving 30+ FPS in real time.",
    "skills": [
      "Data Annotation",
      "AI Model Training"
    ],
    "demo": {
      "type": "video",
      "src": "/projects/Student Behavior Analysis - Skeleton Annotation & GCN Training/Student_Video.mov"
    },
    "thumbnail": "/projects/Student Behavior Analysis - Skeleton Annotation & GCN Training/Student_Video.mov",
    "media": [
      {
        "name": "Student_Video.mov",
        "src": "/projects/Student Behavior Analysis - Skeleton Annotation & GCN Training/Student_Video.mov",
        "type": "video"
      }
    ]
  },
  {
    "id": "verifai-kyc-verification-using-ai",
    "title": "VerifAI [ KYC Verification Using AI ]",
    "info": "VerifAI is an AI-powered identity verification platform that automates the KYC (Know Your Customer) process, enabling organizations to onboard users quickly, securely, and accurately. The system combines OCR, facial recognition, and liveness detection to verify identities in real time while minimizing manual intervention. By digitizing document verification and fraud detection, VerifAI improves operational efficiency and enhances user trust.\n\nKey Features:\n• Extracts information from identity documents using OCR and stores it in a structured format.\n• Captures user location data and live video footage during the verification process.\n• Compares document photos, passport-size photos, and live video using facial recognition.\n• Uses liveness detection to prevent spoofing attacks with photos or prerecorded videos.\n• Auto-fills verification forms and allows users to review or update their information.\n• Instantly verifies genuine users and flags mismatched or suspicious submissions.\n• Reduces onboarding time, manual effort, operational costs, and human error.\n• Suitable for fintech, banking, insurance, and other digital platforms requiring secure KYC compliance.\n• Focuses on privacy, security, speed, and a seamless user experience.",
    "skills": [
      "OCR",
      "Computer Vision",
      "Python",
      "React Native",
      "Django",
      "TenserFlow",
      "Machine Learning"
    ],
    "demo": {
      "type": "video",
      "src": "/projects/VerifAI [ KYC Verification Using AI ]/VerifAI_video.mov"
    },
    "thumbnail": "/projects/VerifAI [ KYC Verification Using AI ]/VerifAI_logo.png",
    "media": [
      {
        "name": "VerifAI_logo.png",
        "src": "/projects/VerifAI [ KYC Verification Using AI ]/VerifAI_logo.png",
        "type": "image"
      },
      {
        "name": "VerifAI_video.mov",
        "src": "/projects/VerifAI [ KYC Verification Using AI ]/VerifAI_video.mov",
        "type": "video"
      }
    ]
  }
];
