// Automatically generated by scripts/generate_reviews_data.cjs
// Do not edit this file manually.

export interface LocalReview {
  id: number
  client: string
  project: string
  location: string
  date: string
  rating: number
  text: string
  category: string
  avatar: string
}

export const LOCAL_REVIEWS: LocalReview[] = [
  {
    "client": "Sarita Shreesh",
    "project": "Editing interview video and making thumbnails.",
    "location": "Nepal",
    "date": "2025-2026",
    "rating": 5,
    "text": "Ghanshyam is a skilled video editor and a creative guy. At Ghumne Kitab, he worked on editing interviews and book reviews, and also created thumbnails for us. He is quick at edits, and good at tight deadlines. He is reliable and easy to work with. Best wishes to him for his career.",
    "category": "External Freelance",
    "avatar": "SS",
    "id": 1
  },
  {
    "client": "Clifford Dongmo",
    "project": "OCR recognition for online workflow integration",
    "location": "Figuil, Cameroon",
    "date": "2025",
    "rating": 4.5,
    "text": "Ghanshyam is a very skilled AI professional. We worked on an OCR project related to education. He was responsive and understood the assignment. He requested from me, a non IT-Guy ;-) all the elements he needed to provide the best solution which fitted all my needs. I was very busy sometimes, but he was always requesting feedbacks, scheduling meetings, and doing his best to finish with the project as scheduled. It was a great journey to work with him on that project.",
    "category": "Upwork",
    "avatar": "CD",
    "id": 2
  },
  {
    "client": "Janet Haastrup",
    "project": "Data Collection Project",
    "location": "Los Angeles, USA",
    "date": "2026",
    "rating": 5,
    "text": "Ghanshyam did an excellent job on this project. He was reliable, detail-oriented, and completed the data collection and curation tasks efficiently within the deadline. Communication was smooth throughout, and the quality of work met expectations. Would be happy to collaborate again.",
    "category": "Upwork",
    "avatar": "JH",
    "id": 3
  }
];
