// Automatically generated by scripts/generate_reviews_data.cjs
// Do not edit this file manually.

export interface LocalReview {
  id: number
  client: string
  project: string
  location: string
  date: string
  rating: number
  text: string
  category: string
  avatar: string
}

export const LOCAL_REVIEWS: LocalReview[] = [
  {
    "client": "Ghumne Kitab",
    "project": "Video Editing",
    "location": "Nepal",
    "date": "June 2025",
    "rating": 5,
    "text": "Ghanshyam is an exceptionally skilled video editor and content creator. He helped us edit and polish our travel vlogs for Ghumne Kitab, delivering high-quality visual cuts and audio synchronization. Highly recommended!",
    "category": "External Freelance",
    "avatar": "GK",
    "id": 1
  },
  {
    "client": "Clifford Dongmo",
    "project": "OCR recognition for online workflow integration",
    "location": "Figuil, Cameroon",
    "date": "2025",
    "rating": 4.5,
    "text": "Ghanshyam is a very skilled AI professional. We worked on an OCR project related to education. He was responsive and understood the assignment. He requested from me, a non IT-Guy ;-) all the elements he needed to provide the best solution which fitted all my needs. I was very busy sometimes, but he was always requesting feedbacks, scheduling meetings, and doing its best to finish with the project as scheduled. It was a great journey to work with him on that project.",
    "category": "Upwork",
    "avatar": "CD",
    "id": 2
  }
];
