const fs = require('fs');
const path = require('path');

const PROJECTS_DIR = path.join(__dirname, '../projects');
const OUTPUT_FILE = path.join(__dirname, '../src/app/constants/projectsData.ts');

function getFiles(dir) {
  return fs.readdirSync(dir).filter(file => !file.startsWith('.'));
}

function parseProjects() {
  const folders = fs.readdirSync(PROJECTS_DIR).filter(file => {
    return fs.statSync(path.join(PROJECTS_DIR, file)).isDirectory();
  });

  const projects = folders.map(folderName => {
    const folderPath = path.join(PROJECTS_DIR, folderName);
    const files = getFiles(folderPath);

    // Parse info.txt
    const infoFile = files.find(f => f.toLowerCase() === 'info.txt');
    const info = infoFile ? fs.readFileSync(path.join(folderPath, infoFile), 'utf-8').trim() : '';

    // Parse Skills.txt or skills.txt
    const skillsFile = files.find(f => f.toLowerCase() === 'skills.txt');
    const skills = skillsFile 
      ? fs.readFileSync(path.join(folderPath, skillsFile), 'utf-8')
          .split('\n')
          .map(s => s.trim())
          .filter(s => s.length > 0)
      : [];

    // Filter media files
    const mediaFiles = files.filter(f => f.toLowerCase() !== 'info.txt' && f.toLowerCase() !== 'skills.txt');
    const images = mediaFiles.filter(f => /\.(png|jpe?g|webp|gif)$/i.test(f));
    const videos = mediaFiles.filter(f => /\.(mp4|mov|webm|ogg)$/i.test(f));
    const pdfs = mediaFiles.filter(f => /\.pdf$/i.test(f));

    // Determine thumbnail
    let thumbnail = '';
    const logoFile = mediaFiles.find(f => f.toLowerCase().includes('logo'));
    const thumbnailFile = mediaFiles.find(f => f.toLowerCase() === 'thumbnail.png');
    if (logoFile) {
      thumbnail = `/projects/${folderName}/${logoFile}`;
    } else if (thumbnailFile) {
      thumbnail = `/projects/${folderName}/${thumbnailFile}`;
    } else if (images.length > 0) {
      thumbnail = `/projects/${folderName}/${images[0]}`;
    } else if (videos.length > 0) {
      // If video, we will use the video path as thumbnail and handle it in the React component
      thumbnail = `/projects/${folderName}/${videos[0]}`;
    } else if (pdfs.length > 0) {
      thumbnail = `/projects/${folderName}/${pdfs[0]}`;
    }

    // Determine demo
    let demo = null;
    if (videos.length > 0) {
      demo = { type: 'video', src: `/projects/${folderName}/${videos[0]}` };
    } else if (pdfs.length > 0) {
      demo = { type: 'pdf', src: `/projects/${folderName}/${pdfs[0]}` };
    } else if (images.length > 0) {
      demo = { type: 'image', src: `/projects/${folderName}/${images[0]}` };
    }

    // List of all media files for gallery
    const allMedia = mediaFiles.map(f => ({
      name: f,
      src: `/projects/${folderName}/${f}`,
      type: /\.(png|jpe?g|webp|gif)$/i.test(f) ? 'image' : /\.(mp4|mov|webm|ogg)$/i.test(f) ? 'video' : 'pdf'
    }));

    return {
      id: folderName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
      title: folderName,
      info,
      skills,
      demo,
      thumbnail,
      media: allMedia
    };
  });

  // Write to src/app/constants/projectsData.ts
  const fileContent = `// Automatically generated by scripts/generate_projects_data.js
// Do not edit this file manually.

export interface ProjectMedia {
  name: string
  src: string
  type: 'image' | 'video' | 'pdf'
}

export interface ProjectDemo {
  type: 'image' | 'video' | 'pdf'
  src: string
}

export interface LocalProject {
  id: string
  title: string
  info: string
  skills: string[]
  demo: ProjectDemo | null
  thumbnail: string
  media: ProjectMedia[]
}

export const LOCAL_PROJECTS: LocalProject[] = ${JSON.stringify(projects, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent, 'utf-8');
  console.log(`Generated ${projects.length} projects into ${OUTPUT_FILE}`);
}

parseProjects();
