const fs = require('fs');
const path = require('path');

const REVIEWS_DIR = path.join(__dirname, '../Review');
const OUTPUT_FILE = path.join(__dirname, '../src/app/constants/reviewsData.ts');

function parseReviewFile(filePath, category) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  
  const data = {
    client: '',
    project: '',
    location: 'Global',
    date: '2025',
    rating: 5,
    text: '',
    category
  };

  const knownKeys = {
    'client': 'client',
    "client's name": 'client',
    'project': 'project',
    'job': 'project',
    'location': 'location',
    "client's location": 'location',
    'date': 'date',
    'year': 'date',
    'rating': 'rating',
    'text': 'text',
    'review': 'text'
  };

  let currentKey = '';

  for (const line of lines) {
    const match = line.match(/^([^:]+)\s*:\s*(.*)$/);
    
    if (match) {
      const parsedKey = match[1].trim().toLowerCase();
      const val = match[2].trim();
      
      if (knownKeys[parsedKey]) {
        currentKey = knownKeys[parsedKey];
        if (currentKey === 'rating') {
          data.rating = parseFloat(val) || 5;
        } else if (currentKey === 'text') {
          data.text = val;
        } else {
          data[currentKey] = val;
        }
      } else {
        // Reset currentKey for metadata fields we don't display
        currentKey = '';
      }
      continue;
    }
    
    // Append to text if in text mode and line is not empty
    if (currentKey === 'text' && line.trim().length > 0) {
      data.text += '\n' + line.trim();
    }
  }

  // Fallbacks if parsing fails
  const fileName = path.basename(filePath, '.txt');
  if (!data.client) {
    data.client = fileName.split('_')[1] || fileName;
  }
  if (!data.project) {
    data.project = fileName.split('_')[0] || 'Freelance Project';
  }
  if (!data.text) {
    data.text = content.trim();
  }

  // Generate avatar initials
  const initials = data.client
    .split(' ')
    .map(w => w[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);
  
  data.avatar = initials || 'CL';

  return data;
}

function parseReviews() {
  const categories = fs.readdirSync(REVIEWS_DIR).filter(file => {
    return fs.statSync(path.join(REVIEWS_DIR, file)).isDirectory();
  });

  let allReviews = [];
  let idCounter = 1;

  for (const cat of categories) {
    const catPath = path.join(REVIEWS_DIR, cat);
    const files = fs.readdirSync(catPath).filter(f => f.endsWith('.txt'));
    
    for (const file of files) {
      const filePath = path.join(catPath, file);
      const review = parseReviewFile(filePath, cat);
      review.id = idCounter++;
      allReviews.push(review);
    }
  }

  const fileContent = `// Automatically generated by scripts/generate_reviews_data.cjs
// Do not edit this file manually.

export interface LocalReview {
  id: number
  client: string
  project: string
  location: string
  date: string
  rating: number
  text: string
  category: string
  avatar: string
}

export const LOCAL_REVIEWS: LocalReview[] = ${JSON.stringify(allReviews, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent, 'utf-8');
  console.log(`Generated ${allReviews.length} reviews into ${OUTPUT_FILE}`);
}

parseReviews();
